// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolvoTrucks.DataAccess;

namespace VolvoTrucks.DataAccess.Migrations
{
    [DbContext(typeof(VolvoTruckContext))]
    [Migration("20201214154720_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VOLVOTRUCKS")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("VolvoTrucks.Domain.Truck", b =>
                {
                    b.Property<int>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("TruckModelId")
                        .HasColumnType("int");

                    b.HasKey("TruckId");

                    b.HasIndex("TruckModelId");

                    b.ToTable("TRUCKS");
                });

            modelBuilder.Entity("VolvoTrucks.Domain.TruckModel", b =>
                {
                    b.Property<int>("TruckModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TruckModelId");

                    b.ToTable("TRUCK_MODELS");

                    b.HasData(
                        new
                        {
                            TruckModelId = 1,
                            Available = true,
                            Model = "FH"
                        },
                        new
                        {
                            TruckModelId = 2,
                            Available = true,
                            Model = "FM"
                        },
                        new
                        {
                            TruckModelId = 3,
                            Available = false,
                            Model = "FMX"
                        },
                        new
                        {
                            TruckModelId = 4,
                            Available = false,
                            Model = "VM"
                        });
                });

            modelBuilder.Entity("VolvoTrucks.Domain.Truck", b =>
                {
                    b.HasOne("VolvoTrucks.Domain.TruckModel", "Model")
                        .WithMany("Trucks")
                        .HasForeignKey("TruckModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("VolvoTrucks.Domain.TruckModel", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
